"""Enhance product model

Revision ID: a8854cba8f6c
Revises: 73fedcab4701
Create Date: 2025-04-16 17:15:43.325042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8854cba8f6c'
down_revision = '73fedcab4701'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('sku', sa.String(), nullable=True))
    op.add_column('products', sa.Column('is_service', sa.Boolean(), nullable=True))
    op.execute("UPDATE products SET is_service = FALSE WHERE is_service IS NULL")
    op.alter_column('products', 'is_service', nullable=False, server_default=sa.text('FALSE'))
    op.add_column('products', sa.Column('price', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('stock_quantity', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('low_stock_threshold', sa.Integer(), nullable=True))
    op.alter_column('products', 'hsn_sac',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('products', 'unit',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.alter_column('products', 'unit',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('products', 'hsn_sac',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('products', 'low_stock_threshold')
    op.drop_column('products', 'stock_quantity')
    op.drop_column('products', 'price')
    op.drop_column('products', 'is_service')
    op.drop_column('products', 'sku')
    # ### end Alembic commands ### 