"""Fix customer model fields

Revision ID: d75c9bf0440d
Revises: fe56224d655a
Create Date: 2025-04-15 18:03:08.573786

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import text


# revision identifiers, used by Alembic.
revision = 'd75c9bf0440d'
down_revision = 'fe56224d655a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customers', 'country', nullable=False, 
                    server_default=text("'India'"),
                    existing_type=sa.String())
    
    # Ensure all existing records have country set to India
    op.execute("UPDATE customers SET country = 'India' WHERE country IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 