"""Add country, city, pincode, notes fields to customers table

Revision ID: fe56224d655a
Revises: 5157a60ec575
Create Date: 2025-04-15 17:39:39.385320

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column
from sqlalchemy import String, select, update


# revision identifiers, used by Alembic.
revision = 'fe56224d655a'
down_revision = '5157a60ec575'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add columns as nullable first
    op.add_column('customers', sa.Column('city', sa.String(), nullable=True))
    op.add_column('customers', sa.Column('country', sa.String(), nullable=True))
    op.add_column('customers', sa.Column('pincode', sa.String(), nullable=True))
    op.add_column('customers', sa.Column('notes', sa.String(), nullable=True))
    
    # Create reference to customers table for updates
    customers = table('customers',
        column('id', sa.Integer),
        column('city', sa.String),
        column('country', sa.String),
        column('pincode', sa.String)
    )
    
    # Update existing records - extract city from address if possible
    # For simplicity, we'll just use same value for city and state
    conn = op.get_bind()
    results = conn.execute(sa.text('SELECT id, state FROM customers'))
    
    for id, state in results:
        conn.execute(
            sa.text('UPDATE customers SET city = :state, country = :country, pincode = :pincode WHERE id = :id'),
            {'state': state, 'country': 'India', 'pincode': '000000', 'id': id}
        )
    
    # Now make columns non-nullable
    op.alter_column('customers', 'city', nullable=False)
    op.alter_column('customers', 'country', nullable=False, server_default='India')
    op.alter_column('customers', 'pincode', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'notes')
    op.drop_column('customers', 'pincode')
    op.drop_column('customers', 'country')
    op.drop_column('customers', 'city')
    # ### end Alembic commands ### 